enabled:
  # s3, dynamodb, redis, startup
  - core_services
  - website
  - tooling
  # disable to save RAM if you don't use portainer or adminer much
  - admin
  # add any specific components you'd like to work with here such
  # as specific tracks runners/analyzers, etc.
  - javascript-test-runner

configure:
  setup:
    build: true
  website:
    build: true

  tooling-orchestrator:
    build: true
  tooling-invoker:
    build: true
  javascript-test-runner-base:
    build: true
  javascript-test-runner:
    build: true
    environment:
      - BOOGER=321

groups:
  core_services:
    - setup
    - redis
    - dynamodb
    - s3
  admin:
    - adminer
    - portainer
  tooling:
    - tooling-invoker
    - tooling-orchestrator
  analyzers:
    - none
  test-runners:
    - csharp-test-runner
    - javascript-test-runner
