name: Rubocop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@b161cb92f0e2f28d992f04f38fff204d84132c47 # 1.71.0
        with:
          ruby-version: 2.6.6

      - name: Install gems
        run: |
          gem install rubocop -v 1.15.0
          gem install rubocop-minitest -v 0.12.1
          gem install rubocop-performance -v 1.11.3

      - name: Run Rubocop
        run: rubocop --except Metrics
