name: Rubocop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@5f29a1cd8dfebf420691c4c9a0e832e2fae5a526
        with:
          ruby-version: 2.6.6

      - name: Install gems
        run: |
          gem install rubocop -v 1.15.0
          gem install rubocop-minitest -v 0.12.1
          gem install rubocop-performance -v 1.11.3

      - name: Run Rubocop
        run: rubocop --except Metrics
